baseurl = "https://muhammadagung.akakom.ac.id/"
languageCode = "en-US"
title = "Muhammad Agung"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  author = "Muhammad Agung Nugroho"
  description = "lecture website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "agungxtwo"
#  Email         = "email@example.com"
#  Twitter       = "username"
  LinkedIn      = "magungnugroho"
#  Stackoverflow = "username"
  Medium        = "agungxtwo"
  Telegram      = "agungxtwo"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
#[[menu.main]]
#  name = "projects"
#  identifier = "projects"
#  weight = 200
#  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
